[package]
name = "tea-intrinsics"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
tea-support = { path = "../tea-support" }
walkdir = "2"
path-clean = "1.0"
pathdiff = "0.2"
